// Run against a local static server: TEST_URL=http://localhost:8765 node tests/browser.cjs
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[],remote=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(!r.url().startsWith(process.env.TEST_URL||'http://localhost:8765'))remote.push(r.url());});
  await page.route('**/ai/worker.js',route=>route.fulfill({contentType:'text/javascript',body:`self.onmessage=({data})=>setTimeout(()=>self.postMessage({type:'result',id:data.id,imageId:data.imageId,backend:'Test worker',suggestions:[{type:'box',label:'dog',score:.9,x:10,y:10,width:80,height:60},{type:'box',label:'cat',score:.35,x:100,y:70,width:50,height:50}]}),300);`}));
  await page.goto(process.env.TEST_URL||'http://localhost:8765');
  const buffer=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=200;c.height=150;const ctx=c.getContext('2d');ctx.fillStyle='#42658b';ctx.fillRect(0,0,200,150);return c.toDataURL().split(',')[1];}),'base64');
  await page.locator('#file').setInputFiles([{name:'same.png',mimeType:'image/png',buffer},{name:'same.png',mimeType:'image/png',buffer}]);
  await page.waitForFunction(()=>document.querySelector('#image-count').textContent==='2 images');
  await page.locator('#overlay').scrollIntoViewIfNeeded();let bounds=await page.locator('#overlay').boundingBox();
  await page.mouse.move(bounds.x+10,bounds.y+10);await page.mouse.down();await page.mouse.move(bounds.x+70,bounds.y+60);await page.mouse.up();
  await page.locator('#new-label').fill('manual');await page.locator('#new-label').press('Enter');
  await page.waitForFunction(()=>document.querySelector('#count').textContent==='1 annotation');
  await page.locator('#ai-detect').click();await page.getByRole('button',{name:'Download & Continue'}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.ai-review-row').length===1);
  assert.equal(await page.locator('#count').textContent(),'1 annotation');
  await page.locator('#ai-threshold').fill('0.3');await page.locator('#ai-threshold').dispatchEvent('input');
  assert.equal(await page.locator('.ai-review-row').count(),2);
  await page.locator('#ai-accept').click();assert.equal(await page.locator('#count').textContent(),'3 annotations');
  await page.locator('#undo').click();assert.equal(await page.locator('#count').textContent(),'1 annotation');
  assert.equal(await page.locator('#tool-smart, #ai-label, #ai-include, #ai-exclude').count(),0);
  await page.locator('#tool-polygon').click();
  for(const position of [{x:20,y:20},{x:120,y:30},{x:70,y:100}])await page.locator('#overlay').click({position});
  await page.locator('#finish-polygon').click();
  await page.locator('#new-label').fill('manual outline');await page.locator('#new-label').press('Enter');
  await page.waitForFunction(()=>document.querySelector('#count').textContent==='2 annotations');
  assert.equal(await page.locator('#count').textContent(),'2 annotations');
  await page.locator('#next').click();assert.equal(await page.locator('#count').textContent(),'0 annotations');
  assert.equal(await page.locator('#ai-overlay polygon').count(),0);
  await page.locator('#ai-detect').click();await page.locator('#previous').click();await page.waitForTimeout(500);
  assert.equal(await page.locator('.ai-review-row').count(),0);assert.equal(await page.locator('#count').textContent(),'2 annotations');
  await page.locator('#ai-detect').click();await page.locator('#ai-cancel').click();await page.waitForTimeout(500);assert.equal(await page.locator('.ai-review-row').count(),0);
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/boundless-ai-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:'/tmp/boundless-ai-desktop.png',fullPage:true});
  assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);
  console.log('Browser passed: manual box, review gating, threshold, accept/undo batch, manual polygon and no AI polygon controls, image isolation, stale results, cancel, mobile layout, no remote requests.');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
